version: '3'
services:
  zookeeper:
    image: confluentinc/cp-zookeeper:7.3.0
    container_name: zookeeper
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000

  broker:
    image: confluentinc/cp-kafka:7.3.0
    container_name: broker
    ports:
      - "9092:9092"
    depends_on:
      - zookeeper
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: 'zookeeper:2181'
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://broker:9092
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
    healthcheck:
      test: [ "CMD", "nc", "-vz", "localhost", "9092" ]
      interval: 10s
      timeout: 5s
      retries: 5

  dapr-placement:
    image: "daprio/dapr:1.9.4"
    command:
      [
        "./placement",
        "-port",
        "50000",
        "-log-level",
        "debug"
      ]
    ports:
      - "50000:50000"
  zipkin:
    image: "openzipkin/zipkin"
    ports:
      - "9411:9411"
  sub-service:
    build:
      context: .
      dockerfile: sub/Dockerfile
    ports:
      - "8081:8081"
    depends_on:
      "broker":
        condition: service_healthy

  sub-api-dapr:
    image: "daprio/daprd:1.9.4"
    network_mode: "service:sub-service"
    command:
      [
        "./daprd",
        "-app-id",
        "sub-service",
        "-app-port",
        "8081",
        "-log-level",
        "debug",
        "-placement-host-address",
        "dapr-placement:50000",
        "-components-path",
        "./dapr/components",
        "-config",
        "./dapr/config.yaml"
      ]
    volumes:
      - "./dapr/:/dapr"
    depends_on:
      "broker":
        condition: service_healthy

  pub-service:
    build:
      context: .
      dockerfile: pub/Dockerfile
    ports:
      - "8080:8080"
    depends_on:
      "broker":
        condition: service_healthy

  pub-api-dapr:
    image: "daprio/daprd:1.9.4"
    network_mode: "service:pub-service"
    command:
      [
        "./daprd",
        "-app-id",
        "pub-service",
        "-app-port",
        "8080",
        "-log-level",
        "debug",
        "-placement-host-address",
        "dapr-placement:50000",
        "-components-path",
        "./dapr/components",
        "-config",
        "./dapr/config.yaml"
      ]
    volumes:
      - "./dapr/:/dapr"
    depends_on:
      "broker":
        condition: service_healthy
        
  redisBasket:
    image: redis:6.2-alpine
    restart: always
    ports:
      - '6379:6379'
    healthcheck:
      test: [ "CMD", "nc", "-vz", "localhost", "6379" ]
      interval: 10s
      timeout: 5s
      retries: 5